# 1. Harris corner detection

- 2차 모멘트 행렬 $\mathbf{A}$가 다음과 같을 때,
$$
\mathbf{A}=\begin{pmatrix} {G * {d_y}^2} & {G * {d_y}{d_x}} \\ {G * {d_y}{d_x}} & {G * {d_x}^2} \end{pmatrix} 
$$

<br>

- $\mathbf{A}$를 다음과 같이 표현하면
$$
\mathbf{A}=\begin{pmatrix} p & r \\ r & q \end{pmatrix} 
$$

<br>

- 특징 가능성 $R$은 다음과 같이 표현됨
$$
R = det(\mathbf{A}) - k \times trace(\mathbf{A})^2  \\ 
= (pq-r^2)-k(p+q)^2
$$

<br>

<img src='rc/harris_region.jpg' alt='harris_region' width="500">


### [reference]
- [link #1 - opencv](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_feature2d/py_features_harris/py_features_harris.html)  
- [link #2 - blog](https://webnautes.tistory.com/1291)

# 2. Practice

In [30]:
import cv2
import numpy as np

## 이미지 읽어오기
img = cv2.imread('chessboard.jpg')
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

## Harris corner 검출
## https://docs.opencv.org/2.4/modules/imgproc/doc/feature_detection.html#cornerharris
dst = cv2.cornerHarris(src = gray,      # 8-bit or floating-point, 1-channel 이미지
                       blockSize = 2,   # 코너 검출 시 고려할 이웃 픽셀의 거리
                       ksize = 3,       # Sobel 마스크의 크기
                       k = 0.04)        # 해리스 코너 검출 조절 파라미터

# (optional) 특징점을 크게 보기 위하여 팽창 모폴로지 연산 수행
dst = cv2.dilate(dst, None)

## 원하는 특징을 검출하기 위한 임계값 설정
# img[dst > 0.01*dst.max()] = [0,0,255]
img[dst > 0.01] = [0,0,255]

## 결과 그리기
cv2.imshow('harris corner', img)
cv2.waitKey()

cv2.destroyAllWindows()

In [22]:
import cv2
import numpy as np

## 이미지 읽어오기
img = cv2.imread('polygon.png')
print(img.shape)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
print(gray.shape)

## Harris corner 검출
## https://docs.opencv.org/2.4/modules/imgproc/doc/feature_detection.html#cornerharris
dst = cv2.cornerHarris(src = gray,      # 8-bit or floating-point, 1-channel 이미지
                       blockSize = 2,   # 코너 검출 시 고려할 이웃 픽셀의 거리
                       ksize = 3,       # Sobel 마스크의 크기
                       k = 0.04)        # 해리스 코너 검출 조절 파라미터
print(dst.shape)

# (optional) 특징점을 크게 보기 위하여 팽창 모폴로지 연산 수행
# dst = cv2.dilate(dst, None, iterations=5)

## 원하는 특징을 검출하기 위한 임계값 설정
# img[dst > 0.01*dst.max()] = [0,0,255]
# img[dst > 0.01] = [0,0,255]
# img[dst < -0.01] = [0,0,255]
img[dst == 0] = [0,0,255]

## 결과 그리기
cv2.imshow('harris corner', img)
# cv2.imwrite('flat.png', img)
cv2.waitKey()

cv2.destroyAllWindows()

(430, 487, 3)
(430, 487)
(430, 487)


In [14]:
a = 3
if 3< a < 5:
    print(1)
else:
    print(0)

0


# ※ Numpy 배열 필터링

In [8]:
import numpy as np

a = np.array([1,2,3])

b = a<=2
print(b)

a[b] = 0
print(a)

[ True  True False]
[0 0 3]


In [6]:
a = np.array([[1,2,3],
             [2,3,4]])

a[a<=2] = 0
print(a)

[[0 0 3]
 [0 3 4]]
